name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build & deploy
        run: npm run deploy
